--1
CREATE PROCEDURE MODULOSDECICLO
	@MODULO NVARCHAR(50)
AS 
	SELECT ASIGNATURA.NOMBRE_ASIGNATURA FROM ASIGNATURA WHERE NOMBRE_CURSO=@MODULO

--2
CREATE PROCEDURE NUMINICIATIVAS
	@CICLO NVARCHAR(50)
AS
	RETURN (SELECT COUNT(ASIGNATURAS_INICIATIVA.COD_INICIATIVA)
			FROM ASIGNATURAS_INICIATIVA
			WHERE ASIGNATURAS_INICIATIVA.NOMBRE_CURSO=@CICLO)

--3
DROP PROCEDURE PROCEDIMIENTO3
CREATE PROCEDURE PROCEDIMIENTO3
	@CICLO NVARCHAR(50)
AS
SELECT INICIATIVAS.TITULO,METAS.DESCRIPCION,ODS.NOMBRE,ASIGNATURAS_INICIATIVA.NOMBRE_CURSO,PROFESORES.NOMBRE_PROFESOR
FROM ((((((ODS
	INNER JOIN METAS ON ODS.NUMERO_ODS=METAS.NUMERO_ODS)
		INNER JOIN METAS_INICIATIVA ON METAS.NUMERO_ODS=METAS_INICIATIVA.NUMERO_ODS
		AND METAS.CARACTER_META=METAS_INICIATIVA.CARACTER_META)
			INNER JOIN INICIATIVAS ON INICIATIVAS.COD_INICIATIVA=METAS_INICIATIVA.COD_INICIATIVA)
				INNER JOIN ASIGNATURAS_INICIATIVA
					ON INICIATIVAS.COD_INICIATIVA=ASIGNATURAS_INICIATIVA.COD_INICIATIVA)
						INNER JOIN ASIGNATURA ON ASIGNATURA.NOMBRE_CURSO=ASIGNATURAS_INICIATIVA.NOMBRE_CURSO
						AND ASIGNATURA.COD_ASIGNATURA=ASIGNATURAS_INICIATIVA.COD_ASIGNATURA)
							INNER JOIN PROFESORES_INICIATIVA
								ON INICIATIVAS.COD_INICIATIVA=PROFESORES_INICIATIVA.COD_INICIATIVA)
									INNER JOIN PROFESORES ON PROFESORES.ID_PROFESOR=PROFESORES_INICIATIVA.ID_PROFESOR
WHERE ASIGNATURAS_INICIATIVA.NOMBRE_CURSO=@CICLO
EXEC PROCEDIMIENTO3 'DAM'
--PROCEDIMIENTO ALMACENADO QUE DEVUELVA EL SIGUIENTE CODIGO DE INICIATIVA DISPONIBLE PARA CREARLOS DESDE VISUAL
CREATE PROCEDURE NUEVOCODIGO
AS
    RETURN ((SELECT MAX(COD_INICIATIVA) +1 FROM INICIATIVAS))

--PROCEDIMIENTO ALMACENADO QUE DEVUELVA NOMBRE Y APELLIDOS DE LOS PROFESORES DE UNA INICIATIVA DADA (CODIGO INICIATIVA)
CREATE PROCEDURE PROFINICIATIVA
    @CODINICIATIVA SMALLINT
AS 
    SELECT CONCAT(NOMBRE_PROFESOR, ' ',APELLIDO1, ' ',APELLIDO2) AS [NOMBRE COMPLETO]
    FROM PROFESORES INNER JOIN (PROFESORES_INICIATIVA INNER JOIN INICIATIVAS ON PROFESORES_INICIATIVA.COD_INICIATIVA = INICIATIVAS.COD_INICIATIVA) ON PROFESORES.ID_PROFESOR = PROFESORES_INICIATIVA.ID_PROFESOR
    WHERE PROFESORES.ID_PROFESOR IN (SELECT ID_PROFESOR FROM PROFESORES_INICIATIVA WHERE COD_INICIATIVA = @CODINICIATIVA)