CREATE DATABASE CUATROVIENTOSRSE
GO
USE CUATROVIENTOSRSE
GO
CREATE TABLE ODS(
	NUMERO_ODS SMALLINT PRIMARY KEY,
	NOMBRE NVARCHAR(50),
	DESCRIPCION NVARCHAR(200),
	IMAGEN NVARCHAR(10)
)

CREATE TABLE CONTRATANTE(
	COD_CONTRATANTE SMALLINT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_CONTRATANTE NVARCHAR(50),
	DESCRIPCION NVARCHAR(500)
)

CREATE TABLE CURSO(
	NOMBRE_CURSO NVARCHAR(50) PRIMARY KEY
)

CREATE TABLE PROFESORES(
	ID_PROFESOR SMALLINT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PROFESOR NVARCHAR(50),
	APELLIDO1 NVARCHAR(50),
	APELLIDO2 NVARCHAR(50),
	FECHA_NACIMIENTO DATE
)

CREATE TABLE METAS(
	NUMERO_ODS SMALLINT NOT NULL,	
	CARACTER_META CHAR(2) NOT NULL,
	DESCRIPCION NVARCHAR(500)
)
ALTER TABLE METAS
ADD CONSTRAINT FK_METAS_ODS FOREIGN KEY (NUMERO_ODS) REFERENCES ODS(NUMERO_ODS)
ALTER TABLE METAS
ADD CONSTRAINT PK_METAS PRIMARY KEY (NUMERO_ODS,CARACTER_META)

CREATE TABLE ASIGNATURA(
	NOMBRE_CURSO NVARCHAR(50) NOT NULL,
	COD_ASIGNATURA SMALLINT IDENTITY(1,1) NOT NULL,
	NOMBRE_ASIGNATURA NVARCHAR(50)
)
ALTER TABLE ASIGNATURA
ADD CONSTRAINT FK_ASIGNATURA_CURSO FOREIGN KEY (NOMBRE_CURSO) REFERENCES CURSO(NOMBRE_CURSO)
ALTER TABLE ASIGNATURA
ADD CONSTRAINT PK_ASIGNATURA PRIMARY KEY (NOMBRE_CURSO,COD_ASIGNATURA)

CREATE TABLE INICIATIVAS(
	COD_INICIATIVA SMALLINT IDENTITY(1,1) PRIMARY KEY,
	HORAS SMALLINT,
	TITULO NVARCHAR(50),
	FECHA_INICIO DATE DEFAULT GETDATE(),
	FECHA_FIN DATE
)

CREATE TABLE PROFESORES_INICIATIVA(
	ID_PROFESOR SMALLINT NOT NULL,
	COD_INICIATIVA SMALLINT NOT NULL
)
ALTER TABLE PROFESORES_INICIATIVA
ADD CONSTRAINT FK_PROFESOR FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID_PROFESOR)
ALTER TABLE PROFESORES_INICIATIVA
ADD CONSTRAINT FK_PROFESOR_INI FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
ALTER TABLE PROFESORES_INICIATIVA
ADD CONSTRAINT PK_PROFESORES_INICIATIVA PRIMARY KEY (ID_PROFESOR,COD_INICIATIVA)

CREATE TABLE CONTRATANTE_INICIATIVA(
	COD_CONTRATANTE SMALLINT NOT NULL,
	COD_INICIATIVA SMALLINT NOT NULL
)
ALTER TABLE CONTRATANTE_INICIATIVA
ADD CONSTRAINT FK_CONTRATANTE FOREIGN KEY (COD_CONTRATANTE) REFERENCES CONTRATANTE(COD_CONTRATANTE)
ALTER TABLE CONTRATANTE_INICIATIVA
ADD CONSTRAINT FK_CONTRATANTE_INI FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
ALTER TABLE CONTRATANTE_INICIATIVA
ADD CONSTRAINT PK_CONTRATANTE_INICIATIVA PRIMARY KEY (COD_CONTRATANTE,COD_INICIATIVA)

CREATE TABLE METAS_INICIATIVA(
	NUMERO_ODS SMALLINT NOT NULL,
	CARACTER_META CHAR(2) NOT NULL,
	COD_INICIATIVA SMALLINT NOT NULL
)

ALTER TABLE METAS_INICIATIVA
ADD CONSTRAINT FK_METAS FOREIGN KEY (NUMERO_ODS,CARACTER_META) REFERENCES METAS(NUMERO_ODS,CARACTER_META)
ALTER TABLE METAS_INICIATIVA
ADD CONSTRAINT FK_METAS_INI FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
ALTER TABLE METAS_INICIATIVA
ADD CONSTRAINT PK_METAS_INICIATIVA PRIMARY KEY (NUMERO_ODS,CARACTER_META,COD_INICIATIVA)

CREATE TABLE ASIGNATURAS_INICIATIVA(
	NOMBRE_CURSO NVARCHAR(50) NOT NULL,
	COD_ASIGNATURA SMALLINT NOT NULL,
	COD_INICIATIVA SMALLINT NOT NULL
)
ALTER TABLE ASIGNATURAS_INICIATIVA
ADD CONSTRAINT FK_ASIGNATURAS FOREIGN KEY (NOMBRE_CURSO,COD_ASIGNATURA) REFERENCES ASIGNATURA(NOMBRE_CURSO,COD_ASIGNATURA)
ALTER TABLE ASIGNATURAS_INICIATIVA
ADD CONSTRAINT FK_ASIGNATURAS_INI FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
ALTER TABLE ASIGNATURAS_INICIATIVA
ADD CONSTRAINT PK_ASIGNATURAS_INICIATIVA PRIMARY KEY (NOMBRE_CURSO,COD_ASIGNATURA,COD_INICIATIVA)

ALTER TABLE INICIATIVAS 
ADD CONSTRAINT CK_FECHA_FIN CHECK (INICIATIVAS.[FECHA_FIN] > INICIATIVAS.[FECHA_INICIO])
ALTER TABLE INICIATIVAS
ADD CONSTRAINT CK_HORAS CHECK (INICIATIVAS.HORAS > 0)
ALTER TABLE PROFESORES
ADD CONSTRAINT CK_FECHA_NACIMIENTO CHECK (PROFESORES.[FECHA_NACIMIENTO] < GETDATE())